"""Add soft deletes and indexes

Revision ID: 053d20ee79fc
Revises: f739827f4f6a
Create Date: 2026-02-13 10:47:40.260439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053d20ee79fc'
down_revision: Union[str, None] = 'f739827f4f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('animals', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_animals_farm_id', 'animals', ['farm_id'], unique=False)
    op.create_index('ix_animals_farm_tag', 'animals', ['farm_id', 'tag_number'], unique=False)
    op.add_column('crops', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('crops', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_crops_farm_id', 'crops', ['farm_id'], unique=False)
    op.add_column('farms', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('farms', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_farms_owner_id', 'farms', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_farms_owner_id', table_name='farms')
    op.drop_column('farms', 'deleted_at')
    op.drop_column('farms', 'is_deleted')
    op.drop_index('ix_crops_farm_id', table_name='crops')
    op.drop_column('crops', 'deleted_at')
    op.drop_column('crops', 'is_deleted')
    op.drop_index('ix_animals_farm_tag', table_name='animals')
    op.drop_index('ix_animals_farm_id', table_name='animals')
    op.drop_column('animals', 'deleted_at')
    op.drop_column('animals', 'is_deleted')
    # ### end Alembic commands ###
