"""Initial Farm Records Schema

Revision ID: 2a854f56ed9d
Revises: 
Create Date: 2026-02-13 12:01:30.483899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a854f56ed9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_unique_constraint(None, 'employees', ['name'])
    op.alter_column('farm_records', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_farm_records_id'), 'farm_records', ['id'], unique=False)
    op.drop_constraint('farm_records_worker_id_fkey', 'farm_records', type_='foreignkey')
    op.create_foreign_key(None, 'farm_records', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_managers_id'), 'managers', ['id'], unique=False)
    op.create_unique_constraint(None, 'managers', ['name'])
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_unique_constraint(None, 'workers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='unique')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_constraint(None, 'managers', type_='unique')
    op.drop_index(op.f('ix_managers_id'), table_name='managers')
    op.drop_constraint(None, 'farm_records', type_='foreignkey')
    op.create_foreign_key('farm_records_worker_id_fkey', 'farm_records', 'workers', ['worker_id'], ['id'])
    op.drop_index(op.f('ix_farm_records_id'), table_name='farm_records')
    op.alter_column('farm_records', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    # ### end Alembic commands ###
